part1 = {
    "A": "Atomic",
    "B": "Blue",
    "C": "Captain",
    "D": "Danger",
    "E": "Electric",
    "F": "Fire",
    "G": "Green",
    "H": "Hyper",
    "I": "Iron",
    "J": "Justice",
    "K": "Killer",
    "L": "Lightning",
    "M": "Magic",
    "N": "Night",
    "O": "Ocean",
    "P": "Purple",
    "Q": "Quantum",
    "R": "Red" ,
    "S": "Super" ,
    "T": "Time" ,
    "U": "Ultra" ,
    "V": "Vision",
    "W": "Wonder" ,
    "X": "X-Ray" ,
    "Y": "Yellow" ,
    "Z": "Zoom"}

part2 = {
    "A": "Crusader",
    "B": "Flame",
    "C": "Ranger",
    "D": "Ferret",
    "E": "Archer",
    "F": "Rider",
    "G": "Samurai",
    "H": "Preacher",
    "I": "Vigilante",
    "J": "Tiger",
    "K": "Hunter",
    "L": "Procupine",
    "M": "Knight",
    "N": "Torch",
    "O": "Blade",
    "P": "Scorpion",
    "Q": "Hurricane",
    "R": "Fang ",
    "S": "Wizard",
    "T": "Wolf",
    "U": "Executioner",
    "V": "Flamingo",
    "W": "Hawk",
    "X": "Brain",
    "Y": "Orchid",
    "Z": "Chinchilla"}

part3 = [
    "The Conquerer",
    "The Seducer",
    "The Champion",
    "The Face",
    "The Hunter",
    "The Savior",
    "The Wizard",
    "The Survivor",
    "The Mighty",
    "The Feared Staff",
    "The Rubber Glove",
    "The Indestructible Force",
    "The Gladiator",
    "The Soldier",
    "The Ruler",
    "The Rebuker",
    "The Wise Oracle",
    "The Hammer",
    "The Plastic Fork",
    "The Aquatic Avenger",
    "The Reaping Soul",
    "The Powerful",
    "The Beautiful",
    "The Skilled Archer",
    "The Wild Amazon",
    "The Sheriff",
    "The Guardian",
    "The Lover",
    "The Unstoppable Force",
    "The Fearless",
    "The Hungry Beast"]

part4 = {
    "A": "Of The Realm",
    "B": "Of Men",
    "C": "Of Justice",
    "D": "Of The Galaxy",
    "E": "Of The Forest",
    "F": "Of the Underworld",
    "G": "Of New Zealand",
    "H": "Of The Living",
    "I": "Of Time Travel",
    "J": "Of The Chosen",
    "K": "Of The Elite Force",
    "L": "Of Christmas Past",
    "M": "Of The North",
    "N": "Of The River",
    "O": "Of The Undead",
    "P": "Of The Space Riders",
    "Q": "Of The Quick",
    "R": "Of The Homeless",
    "S": "Of District 9",
    "T": "Of Atlantis",
    "U": "Of The Tree",
    "V": "Of The Valley",
    "W": "Of The Sub-Humans",
    "X": "Of The Vikings",
    "Y": "Of 7-11",
    "Z": "Of The Celebrated"}






